version: "3.8"
services:
  uav1:
    image: arthur/sitl-copter
    environment:
      SYSID: 1
  uav2:
    image: arthur/sitl-copter
    environment:
      SYSID: 2
  uav3:
    image: arthur/sitl-copter
    environment:
      SYSID: 3
